# Generated by Django 6.0 on 2026-01-08 07:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='photo',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='uploads'),
            preserve_default=False,
        ),
    ]
